---
- name: Update apt and install docker
  hosts: servers
  become: true
  remote_user: tedelin

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install Docker
  hosts: servers
  become: true
  roles:
    - role: docker

- name: Deploy app
  hosts: servers
  roles:
    - role: app



   
