---
- name: Init and docker install
  hosts: all
  strategy: free
  become: true
  roles:
    - init
    - docker

- name: Launch App
  hosts: all
  gather_facts: no
  strategy: free
  become: true
  become_user: cloud-1
  roles:
    - app
