---
- name: Update apt and install docker
  hosts: servers
  become: true
  remote_user: tedelin

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
      keyring: /etc/apt/keyrings/docker.gpg

  - name: Add Docker Repository
    apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable
      state: present
      filename: docker

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin
      state: latest
      update_cache: true

  - name: Add user to docker group
    user:
        name: tedelin
        groups: docker
        append: yes
        state: present

   
