---
- name: Clone repo
  git:
    repo: "{{github_repo}}"
    dest: "{{app_folder}}"
    update: yes
    single_branch: yes
    version: "{{branch}}"

- name: Copy environment variable
  copy: 
    src: ./.env
    dest: "{{ app_folder }}/srcs/.env"
    force: yes

- name: Create Wordpress volume directory
  ansible.builtin.file:
    path: ~/data/wordpress
    state: directory
    mode: '0755'

- name: Create Mariadb volume directory 
  ansible.builtin.file:
    path: ~/data/mariadb
    state: directory
    mode: '0755'

- name: Build Wordpress website
  community.docker.docker_compose_v2:
    project_src: "{{ app_folder }}/srcs"
    build: always
  register: output