---
- name: Clone repo
  git:
    repo: "{{github_repo}}"
    dest: "{{app_folder}}"
    update: yes
    single_branch: yes
    version: "{{branch}}"

- name: Copy environment variable
  copy: 
    src: ./.env
    dest: "{{ app_folder }}/srcs/.env"
    force: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Build Wordpress website
  shell:
      cmd: make
      chdir: "{{ app_folder }}"