---
- name: Clone repo
  git:
    repo: {{github_repo}}
    dest: {{app_folder}}
    update: yes
    single_branch: yes
    version: {{branch}}

- name: Copy environment variable
  copy: 
    src: ./.env
    dest: "{{ app_folder }}/srcs/.env"

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

# - name: deploy app with docker compose
#   shell:
#       cmd: make
#       chdir: "{{ app_folder }}/Inception"

- name: Deploy Docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ app_folder }}/srcs"
    files:
      - docker-compose.yml