---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install build-essential
  become: true
  apt:
    name: build-essential
    state: latest
    update_cache: true

- name: Create cloud-1 user
  become: true
  ansible.builtin.user:
    name: cloud-1
    create_home: yes
    groups: sudo
    append: yes

- name: Ensure remote_tmp directory exists with correct permissions
  file:
    path: "/home/cloud-1/.ansible/tmp"
    state: directory
    mode: '1777'